### ISSUE TITLE
Documentation/resource_cn/使用C++编写智能合约.md

### ISSUE THREAD

**Issue by duncanwang** [bottos-project/Documentation#6]
V3.5版本上线后， gettable 已不存在account的账号了。

【位置】

合约正确执行后，则保存至链上的数据valueA和valueB分别是2和3，可以通过如下命令进行查询：

./bcli  gettable --account testdbsaveread --table testTableName --key testKeyName
{
    "contract": "testdbsaveread",
    "object": "testTableName",
    "key": "testKeyName",
    "value": "dc0002ce00000002ce00000003"
}

Table data is : map[valueA:2 valueB:3]

**Comment by wesley-zh** [comment]
fixed @ 7d75c886b9727c9ebc3fd7f388d8b1a0a85f9c6a
